static_pages:
  home:
    image_size: 200px
links:
  rails_tutorial:
    home_page: "https://www.railstutorial.org/"
    help_page: "https://www.railstutorial.org/help"
    book_page: "https://www.railstutorial.org/book"
    screencasts_page: "https://screencasts.railstutorial.org/"
    contact_page: "https://www.railstutorial.org/contact"
    new_page: "https://news.railstutorial.org/"
    author: "https://www.michaelhartl.com/"
  learn_enough: "https://www.learnenough.com/"
  gravatar: "https://secure.gravatar.com/avatar/"
validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
sessions:
  create:
    select_box: 1
users:
  gravatar: "https://gravatar.com/emails"
  avatar_size: 80
list_users:
  avatar_size: 50
  pagination: 20
password_reset_expired: 2
content_attribute:
  max_length: 140
avatar_size_micropost: 50
items_per_pages: 30
micropost:
  content:
    length_max: 140
  image:
    size: 5
    resize_to_limit: 500
    accept_type: "image/jpeg,image/gif,image/png"
    content_type: %w(image/jpeg image/gif image/png)
micropost_per_homepages: 9
files:
  image_type: /%w(image/jpeg image/gif image/png)/
  valid_input: image/jpeg,image/gif,image/png
  pic_resize: 500
  pic_size: 5
  change_digit: 1048576
